import React from "react";
import { CgWorkAlt } from "react-icons/cg";
import { LuGraduationCap, LuHelpingHand, LuUser2 } from "react-icons/lu";

import type { Experience } from "./types";

export const experiences: readonly Experience[] = [
  {
    slug: "ripplet-founding-engineer",
    locationUrl: "https://ripplet-info-website.vercel.app/",
    icon: React.createElement(CgWorkAlt),
    isBulletPoints: true,
    copy: {
      en: {
        title: "Founding Engineer",
        location: "Ripplet - Remote",
        date: "Jun 2024 - Aug 2025",
        description: [
          "Ripplet is a storytelling and healing platform uplifting the voices of immigrants, Black, Indigenous, and People of Color (BIPOC) communities, and those living between cultures through podcasts, expressive arts, and community-led narratives",
          "Conducted user interviews, competitive analysis, and product research to identify critical pain points and refine solution offerings",
          "Designed and developed the company website, delivering a responsive and user-friendly interface",
          "Built a therapist support platform prototype with an AI-powered chatbot and dashboards, enabling secure session notes, evidence-based guidance, and progress tracking",
        ],
        tags: [
          "Multi-agent Systems",
          "Ollama",
          "OpenAI API",
          "Next.js",
          "Google Gemini",
          "Anthropic Claude",
          "LlamaIndex",
          "Hugging Face Products",
          "LangChain",
          "Redux",
          "Node.js",
          "Prompt Engineering",
          "Software Development",
          "React.js",
          "Python (Programming Language)",
          "TailwindCSS",
          "PostgreSQL",
          "Retrieval-Augmented Generation (RAG)",
          "U.S. Health Insurance Portability and Accountability Act (HIPAA)",
          "Django REST Framework",
        ],
      },
      cn: {
        title: "创始工程师",
        location: "Ripplet - 远程",
        date: "2024年6月 - 2025年8月",
        description: [
          "Ripplet 是一个讲述与疗愈平台，通过播客、表达性艺术和社区主导的叙事，提升移民、黑人、土著及有色人种（BIPOC）社群以及跨文化群体的声音",
          "开展用户访谈、竞品分析和产品研究，以识别关键痛点并优化解决方案",
          "设计并开发公司官网，实现响应式且用户友好的界面",
          "构建了一个治疗师支持平台原型，集成 AI 驱动的聊天机器人与交互式仪表盘，实现安全的会话记录、循证指导和进度追踪",
        ],
        tags: [
          "美国健康保险可携性与责任法案 (HIPAA)",
          "多智能体系统",
          "Ollama",
          "OpenAI API",
          "Next.js",
          "Google Gemini",
          "Anthropic Claude",
          "LlamaIndex",
          "Hugging Face 产品",
          "LangChain",
          "Redux",
          "Node.js",
          "提示工程 (Prompt Engineering)",
          "软件开发",
          "React.js",
          "Python 编程语言",
          "TailwindCSS",
          "PostgreSQL",
          "Django REST 框架",
          "检索增强生成 (RAG)",
        ],
      },
    },
  },
  {
    slug: "bobatalks-mentor",
    locationUrl: "https://www.bobatalks.com/",
    icon: React.createElement(LuHelpingHand),
    isBulletPoints: false,
    copy: {
      en: {
        title: "Mentor",
        location: "BobaTalks",
        date: "Feb 2025 - Present",
        description: [
          "Support international students and newcomers to tech in figuring out their path, from deciding on graduate school to exploring career directions and navigating challenges abroad",
        ],
        tags: [
          "Mentorship",
          "International Students",
          "Career Guidance",
          "Graduate School Advice",
        ],
      },
      cn: {
        title: "导师",
        location: "BobaTalks",
        date: "2025年2月 - 现在",
        description: [
          "支持国际学生和科技新手规划职业路径，包括研究生院选择、职业方向探索及海外生活挑战应对。",
        ],
        tags: ["导师", "国际学生", "职业指导", "研究生院建议"],
      },
    },
  },
  {
    // NOTE: the old data.ts used a briefcase icon in English and a graduation
    // cap in Chinese for this one entry, so the icon changed when you toggled
    // language. Settled on the briefcase, matching the other UCSC tutor role.
    slug: "ucsc-deep-learning-tutor",
    locationUrl: "https://www.ucsc.edu/",
    icon: React.createElement(CgWorkAlt),
    isBulletPoints: true,
    copy: {
      en: {
        title: "Individual Tutor and Grader - Deep Learning Course",
        location: "UC Santa Cruz - Santa Cruz, CA",
        date: "Sep 2024 - Dec 2024",
        description: [
          "Held in-person and remote office hours twice weekly to clarify deep learning concepts, and guided students in applying machine learning principles, including model training/testing, loss functions, gradient descent, and regularization techniques",
          "Graded coding assignments and quizzes, providing constructive feedback on topics such as CNNs, RNNs, attention models, and transformers",
        ],
        tags: [
          "Deep Learning",
          "Neural Networks",
          "Machine Learning",
          "Reinforcement Learning",
          "Python Programming",
          "Communication",
        ],
      },
      cn: {
        title: "一对一课程辅导与作业评分 - 深度学习课程",
        location: "加州大学圣克鲁兹分校 - 圣克鲁兹, 加州",
        date: "2024年9月 - 2024年12月",
        description: [
          "每周两次线上与线下答疑，讲解深度学习核心概念，并指导学生应用机器学习原理，包括模型训练/测试、损失函数、梯度下降以及正则化技术",
          "批改编程作业与小测验，并针对卷积神经网络 (CNN)、循环神经网络 (RNN)、注意力模型和 Transformer 等主题提供建设性反馈",
        ],
        tags: [
          "深度学习",
          "神经网络",
          "机器学习",
          "强化学习",
          "Python 编程",
          "沟通能力",
        ],
      },
    },
  },
  {
    slug: "ucsc-graduate-student",
    locationUrl: "https://www.ucsc.edu/",
    icon: React.createElement(LuGraduationCap),
    isBulletPoints: false,
    copy: {
      en: {
        title: "Graduate Student",
        location: "UC Santa Cruz - Santa Cruz, CA",
        date: "Sep 2024 - Dec 2025 (Expected Graduation)",
        description: ["Master of Science in Computer Science and Engineering"],
        tags: [
          "Machine Learning",
          "Foundations of Deep Learning",
          "Projects in Artificial Intelligence",
          "Artificial Intelligence in Games",
          "Advanced Computer Security",
          "Computer Security and Network",
          "VLSI Digital System Design",
          "Analysis of Algorithms",
          "Programming Languages - Coq",
          "Formal Methods",
          "Research and Teaching in Computer Science and Engineering",
        ],
      },
      cn: {
        title: "研究生",
        location: "加州大学圣克鲁兹分校 - 圣克鲁兹, 加州",
        date: "2024年9月 - 预计2025年12月",
        description: ["攻读计算机科学与工程硕士学位"],
        tags: [
          "机器学习",
          "深度学习基础",
          "人工智能项目",
          "高级计算机安全",
          "计算机安全与网络",
          "超大规模集成电路数字系统设计",
          "算法分析",
          "编程语言——Coq（证明辅助工具/形式化语言）",
          "形式化方法",
          "计算机科学与工程中的研究与教学",
        ],
      },
    },
  },
  {
    slug: "tech4good-dev-lead",
    locationUrl: "https://tech4good.soe.ucsc.edu/",
    icon: React.createElement(CgWorkAlt),
    isBulletPoints: false,
    copy: {
      en: {
        title: "Full Stack Engineer & Dev Lead - AI Pathways Team",
        location: "Tech4Good Lab - Santa Cruz, CA",
        date: "June 2023 - Jan 2025",
        description: [
          "Led a cross-functional team of AI researchers, web developers, and UI/UX designers to build Pathways, an AI-powered self-directed learning platform that helps anyone learn—from coding to cooking—through personalized recommendations and interactive guidance, refined through multiple user studies, including pilots with university students.",
        ],
        tags: [
          "Prompt Engineering",
          "LLMLingua/LongLLMLingua",
          "Pinecone",
          "OpenAI ChatCompletion API",
          "OpenAI Assistant API",
          "OpenAI Embeddings API",
          "User Research",
          "Leadership",
          "Mentorship",
        ],
      },
      cn: {
        title: "全栈工程师 & 开发负责人 - AI Pathways 团队",
        location: "Tech4Good 实验室 - 美国加州圣克鲁兹",
        date: "2023年6月 - 2025年1月",
        description: [
          "带领由 AI 研究员、网页开发者和 UI/UX 设计师组成的跨职能团队，开发 Pathways —— 一个由人工智能驱动的自我导向学习平台，帮助用户学习从编程到烹饪等各类主题。平台通过个性化推荐与交互式指导实现学习体验，并经过多次用户研究验证与优化，包括在大学生群体中的试点实验。",
        ],
        tags: [
          "提示工程 (Prompt Engineering)",
          "LLMLingua/LongLLMLingua",
          "Pinecone",
          "OpenAI ChatCompletion API",
          "OpenAI Assistant API",
          "OpenAI Embeddings API",
          "用户研究",
          "领导力",
          "导师指导",
        ],
      },
    },
  },
  {
    slug: "code-for-fun-instructor",
    locationUrl: "https://codeforfun.com/",
    icon: React.createElement(CgWorkAlt),
    isBulletPoints: true,
    copy: {
      en: {
        title: "Coding Instructor",
        location: "Code For Fun - Sunnyvale, CA",
        date: "Feb 2023 - Feb 2024",
        description: [
          "Taught K–12 students fundamental programming concepts, including logic, problem-solving, and introductory data structures & algorithms",
          "Led large-scale Code Day workshops for up to 300 students and taught in small (1–8) and medium-to-large (8–25) class settings",
          "Developed project-based curricula and delivered engaging lessons in: Game Development, Robotics, Web Development, Mobile App Development, Block-based Programming and Text-based Programming",
        ],
        tags: [
          "Teaching",
          "Public Speaking",
          "Game Development",
          "Web Development",
          "Mobile App Development",
          "Block Programming",
          "Python",
          "Lua (Roblox)",
          "JavaScript",
          "HTML",
          "CSS",
          "Scratch",
        ],
      },
      cn: {
        title: "编程讲师",
        location: "Code For Fun - 美国加州森尼韦尔",
        date: "2023年2月 - 2024年2月",
        description: [
          "教授 K–12 学生编程基础概念，包括逻辑思维、问题求解，以及入门级数据结构与算法",
          "主持最多可容纳 300 名学生的大型 Code Day 编程工作坊，并在小班（1–8 人）及中大班（8–25 人）教学环境中授课",
          "设计基于项目的课程，并教授涵盖以下方向的实践课程：游戏开发、机器人开发、网页开发、移动应用开发、图形化编程与文本编程",
        ],
        tags: [
          "教学",
          "公众演讲",
          "游戏开发",
          "网页开发",
          "移动应用开发",
          "图形化编程",
          "Python",
          "Lua (Roblox)",
          "JavaScript",
          "HTML",
          "CSS",
          "Scratch",
        ],
      },
    },
  },
  {
    slug: "ucsc-undergraduate-student",
    locationUrl: "https://www.ucsc.edu/",
    icon: React.createElement(LuGraduationCap),
    isBulletPoints: true,
    copy: {
      en: {
        title: "Undergraduate Student",
        location: "UC Santa Cruz - Santa Cruz, CA",
        date: "July 2020 - Dec 2022",
        description: [
          "Bachelor of Science (B.S.) in Computer Science and Engineering",
          "Bachelor of Arts (B.A.) in Psychology",
        ],
        tags: [
          "Data Structure and Algorithm",
          "Analysis of Algorithms",
          "Computational Models",

          "Embedded Systems and C Programming",
          "Computer Systems and Assembly Language",
          "Computer Architecture",
          "Principles of Computer Systems Design",

          "Programming in Python",
          "Programming Abstractions: Python",
          "Foundations of Programming Languages (Haskell)",

          "Computer Graphics",
          "Artificial Intelligence",
          "Applied Machine Learning",
          "Natural Language Processing",
          "Technical Writing for Computer Science and Engineering",

          "Statistics",
          "Applied Discrete Mathematics",

          "Abnormal Psychology",
          "Developmental Psychology",
          "Lifespan Developmental Psychopathology",
          "Children's Thinking",
          "Human Learning and Memory",
          "Research Methods in Psychology",
        ],
      },
      cn: {
        title: "本科生",
        location: "UC Santa Cruz - Santa Cruz, CA",
        date: "2020年7月 - 2022年12月",
        description: [
          "计算机科学与工程 理学学士 (B.S.)",
          "心理学 文学学士 (B.A.)",
        ],
        tags: [
          "数据结构与算法",
          "算法分析",
          "计算模型",

          "嵌入式系统与C编程",
          "计算机系统与汇编语言",
          "计算机架构",
          "计算机系统设计原理",

          "Python编程",
          "Python编程抽象",
          "编程语言基础（Haskell）",

          "计算机图形学",
          "人工智能",
          "应用机器学习",
          "自然语言处理",
          "计算机科学与工程技术写作",

          "统计学",
          "离散数学应用",

          "异常心理学",
          "发展心理学",
          "生命周期发展心理病理学",
          "儿童思维",
          "人类学习与记忆",
          "心理学研究方法",
        ],
      },
    },
  },
  {
    slug: "ucsc-python-grader",
    locationUrl: "https://www.ucsc.edu/",
    icon: React.createElement(CgWorkAlt),
    isBulletPoints: true,
    copy: {
      en: {
        title: "Grader & Tutor for Python",
        location: "UC Santa Cruz - Santa Cruz, CA",
        date: "Apr 2021 - Dec 2022",
        description: [
          "Graded Python programming assignments using automated grading scripts to ensure accuracy and consistency across submissions",
          "Assisted students in understanding course concepts and debugging code during office hours and online forums",
          "Rehired by the same professor for eight consecutive quarters based on performance and reliability",
        ],
        tags: ["Tutoring", "Python", "Communication", "Problem Solving"],
      },
      cn: {
        title: "Python 课程评分员与辅导员",
        location: "加州大学圣克鲁兹分校 - 美国加州圣克鲁兹",
        date: "2021年4月 - 2022年12月",
        description: [
          "使用自动化评分脚本批改 Python 编程作业，确保提交结果的准确性与一致性",
          "在答疑时间和在线论坛中，协助学生理解课程概念并调试代码",
          "因表现与可靠性突出，连续八个学期被同一位教授再次聘用",
        ],
        tags: ["课程辅导", "Python", "沟通能力", "问题解决"],
      },
    },
  },
  {
    slug: "wayops-backend-intern",
    locationUrl: "https://wayops.eu/",
    icon: React.createElement(CgWorkAlt),
    isBulletPoints: false,
    copy: {
      en: {
        title: "Backend Developer Intern",
        location: "WayOps - Remote",
        date: "Jul 2021 - Aug 2021",
        description: [
          "Contributed to a smart parking management system by reorganizing large-scale datasets for efficiency, improving query speed, and database scalability to support real-time parking availability insights.",
        ],
        tags: [
          "Collaboration",
          "SQL",
          "PostgreSQL",
          "Database Optimization",
          "Data Modeling",
          "Relational Databases",
          "Scalability & Performance Tuning",
          "Azure Data Studio",
        ],
      },
      cn: {
        title: "后端开发实习生",
        location: "WayOps - 远程",
        date: "2021年7月 - 2021年8月",
        description: [
          "参与智能停车管理系统开发，通过重组大规模数据集提升效率，改进查询速度和数据库可扩展性，以支持实时停车位可用性分析",
        ],
        tags: [
          "协作",
          "SQL",
          "PostgreSQL",
          "数据库优化",
          "数据建模",
          "关系型数据库",
          "可扩展性与性能调优",
          "Azure Data Studio",
        ],
      },
    },
  },
  {
    slug: "hssv-animal-care-volunteer",
    locationUrl: "https://www.hssv.org/",
    icon: React.createElement(LuHelpingHand),
    isBulletPoints: true,
    copy: {
      en: {
        title: "Animal Care Volunteer",
        location: "Humane Society at Silicon Valley - Sunnyvale, CA",
        date: "June 2018 - June 2019",
        description: [
          "Provided compassionate, hands-on care to dogs, cats, and rabbits, enriching their lives and preparing them for adoption into loving homes",
          "Focused on ensuring the well-being and comfort of the animals",
        ],
        tags: [
          "Compassion and Empathy",
          "Responsibility",
          "Reliability",
          "Time Management",
        ],
      },
      cn: {
        title: "动物领养中心志愿者",
        location: "Humane Society at Silicon Valley - Sunnyvale, CA",
        date: "2018年6月 - 2019年6月",
        description: [
          "提供同情和实际的护理给狗、猫和兔子，丰富他们的生活，并准备他们进入充满爱的家庭。",
          "专注于确保动物的福祉和舒适。",
        ],
        tags: ["同情心和同理心", "责任心", "可靠性", "时间管理能力"],
      },
    },
  },
  {
    slug: "de-anza-pop-music-club",
    locationUrl: "https://www.deanza.edu/",
    icon: React.createElement(LuUser2),
    isBulletPoints: true,
    copy: {
      en: {
        title: "Co-founder & President - Pop Music Club",
        location: "De Anza College - Cupertino, CA",
        date: "May 2017 - June 2020",
        description: [
          "Co-founded and led a music club with over 200 members, serving as president for two years",
          "Managed bands and organized events, including annual concerts and club days",
        ],
        tags: [
          "Leadership",
          "Teamwork",
          "Communication",
          "Problem Solving",
          "Planning and organizing events",
        ],
      },
      cn: {
        title: "社团创始人兼主席 - Pop Music Club",
        location: "De Anza College - Cupertino, CA",
        date: "2017年5月 - 2020年6月",
        description: [
          "与他人共同创立并领导了一个拥有200多名成员的音乐社团，担任主席两年。",
          "管理乐队并组织活动，包括年度音乐会和俱乐部日。",
        ],
        tags: ["领导力", "团队合作", "沟通能力", "解决问题能力", "规划和组织活动"],
      },
    },
  },
  {
    slug: "de-anza-cpp-ta",
    locationUrl: "https://www.deanza.edu/",
    icon: React.createElement(LuHelpingHand),
    isBulletPoints: true,
    copy: {
      en: {
        title:
          "Teaching Assistant - C++ Programming Courses (Beginning to Advanced)",
        location: "De Anza College - Cupertino, CA",
        date: "Apr 2018 - June 2019",
        description: [
          "Assisted in teaching C++ programming courses ranging from beginner to advanced levels",
          "Held office hours to help students with coding problems and concepts",
          "Graded assignments and provided feedback to students",
        ],
        tags: ["Teaching", "C++", "Student Support"],
      },
      cn: {
        title: "教学助理 - C++ 编程课程（初级到高级）",
        location: "De Anza 学院 - 美国加州库比蒂诺",
        date: "2018年4月 - 2019年6月",
        description: [
          "协助教授从入门到高级的 C++ 编程课程",
          "在答疑时间帮助学生解决编程问题和理解相关概念",
          "批改作业并为学生提供反馈",
        ],
        tags: ["教学", "C++", "学生支持"],
      },
    },
  },
  {
    slug: "de-anza-cis-lab-tutor",
    locationUrl: "https://www.deanza.edu/",
    icon: React.createElement(LuHelpingHand),
    isBulletPoints: true,
    copy: {
      en: {
        title: "CIS Lab Tutor",
        location: "De Anza College - Cupertino, CA",
        date: "Apr 2018 - June 2019",
        description: [
          "Worked as a lab tutor for Computer Information Systems (CIS) courses, providing hands-on assistance to students during lab sessions.",
          "Helped students understand course material, debug code, and complete lab assignments.",
          "Collaborated with instructors to identify common student challenges and develop effective teaching strategies.",
        ],
        tags: ["Teaching", "C++", "Student Support"],
      },
      cn: {
        title: "CIS 实验室辅导员",
        location: "De Anza 学院 - 美国加州库比蒂诺",
        date: "2018年4月 - 2019年6月",
        description: [
          "担任计算机信息系统 (CIS) 课程的实验室辅导员，在实验课期间为学生提供实践性指导",
          "帮助学生理解课程内容、调试代码并完成实验作业",
          "与授课教师合作，识别学生常见难点并制定有效的教学策略",
        ],
        tags: ["教学", "C++", "学生支持"],
      },
    },
  },
  {
    slug: "de-anza-student",
    locationUrl: "https://www.deanza.edu/",
    icon: React.createElement(LuGraduationCap),
    isBulletPoints: false,
    copy: {
      en: {
        title: "Community College Student",
        location: "De Anza College - Cupertino, CA",
        date: "Apr 2016 - June 2020",
        description: [
          "Completed required coursework for a Computer Science degree before transferring to UC Santa Cruz",
        ],
        tags: [
          "C++",
          "Java",
          "Python",
          "Assembly Language",
          "Physics",
          "Chemistry",
          "Pre-Calculus",
          "Calculus",
          "Discrete Mathematics",
        ],
      },
      cn: {
        title: "社区大学学生",
        location: "De Anza College - Cupertino, CA",
        date: "2016年4月 - 2020年6月",
        description: ["在转学之前完成了计算机科学学位所需的课程。"],
        tags: [
          "C++",
          "Java",
          "Python",
          "汇编语言",
          "物理",
          "化学",
          "预微积分",
          "微积分",
          "离散数学",
        ],
      },
    },
  },
];
